org: lemonearthchoco
app: myfo-image-api
service: myfo-image-api
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    APP_NAME: ${env.APP_NAME}
    S3_BUCKET: ${env.S3_BUCKET}
    AWS_REGION: ${env.AWS_REGION}


custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: 'node16'
    define: { 'require.resolve': undefined }
    platform: 'node'
    concurrency: 10

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin
package:
  individually: true

functions:
  imageUploadHandler:
    handler: handler.imageUploadHandler
    events:
      - httpApi:
          path: /myfo/images
          method: post
