service: myfo-image-api
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    APP_NAME: ${env.APP_NAME}
    S3_BUCKET: ${env.S3_BUCKET}
    REGION: ${env.REGION}
  region: ap-northeast-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"       # 객체 업로드 권한
        - "s3:PutObjectAcl"    # ACL 설정 권한 (예: public-read)
      Resource:
        - "arn:aws:s3:::lemonearthchoco/*"


custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: 'node16'
    define: { 'require.resolve': undefined }
    platform: 'node'
    concurrency: 10

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin
package:
  individually: true

functions:
  imageUploadHandler:
    handler: handler.imageUploadHandler
    events:
      - httpApi:
          path: /myfo/images
          method: post
